package afp_labor_a_kliens;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Tüzes
 */
public class Employee_list extends javax.swing.JFrame {
        public static int index;
    /**
     * Creates new form Employee_list
     */
    public Employee_list() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(0, 153, 0) );
        setTitle("Dolgozó lista");
    }

    public void list(String[] lista) throws ClassNotFoundException {
        try {
            
           DefaultListModel listModel = new DefaultListModel();
           //subList( 1, lista.length )
           lista = Arrays.copyOfRange(lista, 1, lista.length);
           for (String i : lista) { 
               listModel.addElement(i);
           }
           
           jList1.setModel(listModel);
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Hiba történt");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dolgozoklistaja_szoveg = new javax.swing.JTextPane();
        Button_kilepes = new javax.swing.JButton();
        Button_felvitel = new javax.swing.JButton();
        copyright = new javax.swing.JTextPane();
        dolgozo_lista = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Button_frissites = new javax.swing.JButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dolgozoklistaja_szoveg.setBackground(new java.awt.Color(0, 0, 0));
        dolgozoklistaja_szoveg.setFont(new java.awt.Font("Arial Black", 0, 21)); // NOI18N
        dolgozoklistaja_szoveg.setForeground(new java.awt.Color(255, 255, 255));
        dolgozoklistaja_szoveg.setText("Dolgozók listája");
        dolgozoklistaja_szoveg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dolgozoklistaja_szoveg.setFocusable(false);

        Button_kilepes.setBackground(new java.awt.Color(204, 0, 0));
        Button_kilepes.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Button_kilepes.setText("Kilépés");
        Button_kilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_kilepesActionPerformed(evt);
            }
        });

        Button_felvitel.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Button_felvitel.setText("Felvitel");
        Button_felvitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_felvitelActionPerformed(evt);
            }
        });

        copyright.setBackground(new java.awt.Color(0, 153, 0));
        copyright.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 255, 255));
        copyright.setText("Copyright mindenség");
        copyright.setFocusable(false);

        jList1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        dolgozo_lista.setViewportView(jList1);

        Button_frissites.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Button_frissites.setText("FRISSÍTÉS");
        Button_frissites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_frissitesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dolgozoklistaja_szoveg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_frissites)
                        .addGap(18, 18, 18)
                        .addComponent(Button_felvitel)
                        .addGap(18, 18, 18)
                        .addComponent(Button_kilepes))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dolgozo_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dolgozoklistaja_szoveg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_kilepes)
                        .addComponent(Button_felvitel)
                        .addComponent(Button_frissites)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(dolgozo_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            
            
            
            
            
            
            
            AFP_Labor_A_Kliens.uzenet = "listazas";
        } catch (Exception e) {
              System.out.println(e.getMessage());
              JOptionPane.showMessageDialog(null, "Hiba: " + e.getMessage(), "Hiba", JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_formWindowOpened

    private void Button_felvitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_felvitelActionPerformed
        new Employee_add().setVisible(true);
    }//GEN-LAST:event_Button_felvitelActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
    if (evt.getClickCount() == 2) {
        try {
        index = jList1.locationToIndex(evt.getPoint());
        System.out.println("index: "+index);
        
            AFP_Labor_A_Kliens.db.dolgozoldal(index);
            //Employee_page empage = new Employee_page();
            //empage.setVisible(true);
            //Employee_page.betolt();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Employee_list.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }//GEN-LAST:event_jList1MouseClicked

    private void Button_kilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_kilepesActionPerformed
dispose();
    }//GEN-LAST:event_Button_kilepesActionPerformed

    private void Button_frissitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_frissitesActionPerformed
        try {
            
            AFP_Labor_A_Kliens.uzenet = "listazas";
        } catch (Exception e) {
              System.out.println(e.getMessage());
              JOptionPane.showMessageDialog(null, "Hiba: " + e.getMessage(), "Hiba", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Button_frissitesActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_list().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_felvitel;
    private javax.swing.JButton Button_frissites;
    private javax.swing.JButton Button_kilepes;
    private javax.swing.JTextPane copyright;
    private javax.swing.JScrollPane dolgozo_lista;
    private javax.swing.JTextPane dolgozoklistaja_szoveg;
    private javax.swing.JList<String> jList1;
    // End of variables declaration//GEN-END:variables
}
