/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afp_labor_a_kliens;

import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tüzes
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    
    
    public Registration() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(0, 153, 0) );
        setTitle("Regisztráció");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regisztralas_szoveg = new javax.swing.JTextPane();
        nev_regisztracio = new javax.swing.JTextField();
        jelszo_regisztracio = new javax.swing.JPasswordField();
        jelszomegint_regisztracio = new javax.swing.JPasswordField();
        Button_kesz = new javax.swing.JButton();
        copyright = new javax.swing.JTextPane();
        Button_kilepes = new javax.swing.JButton();

        setResizable(false);

        regisztralas_szoveg.setEditable(false);
        regisztralas_szoveg.setBackground(new java.awt.Color(0, 0, 0));
        regisztralas_szoveg.setFont(new java.awt.Font("Arial Black", 0, 21)); // NOI18N
        regisztralas_szoveg.setForeground(new java.awt.Color(255, 255, 255));
        regisztralas_szoveg.setText("Regisztrálás");
        regisztralas_szoveg.setFocusable(false);

        nev_regisztracio.setText("Név");
        nev_regisztracio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nev_regisztracioActionPerformed(evt);
            }
        });

        jelszo_regisztracio.setText("Jelszó");

        Button_kesz.setText("Kész");
        Button_kesz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_keszActionPerformed(evt);
            }
        });

        copyright.setBackground(new java.awt.Color(0, 153, 0));
        copyright.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 255, 255));
        copyright.setText("Copyright mindenség");
        copyright.setFocusable(false);

        Button_kilepes.setBackground(new java.awt.Color(204, 0, 0));
        Button_kilepes.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Button_kilepes.setText("Kilépés");
        Button_kilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_kilepesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 363, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(regisztralas_szoveg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(373, 373, 373))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jelszomegint_regisztracio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jelszo_regisztracio, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nev_regisztracio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Button_kesz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)))
                                .addGap(357, 357, 357))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_kilepes)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Button_kilepes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regisztralas_szoveg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(nev_regisztracio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jelszo_regisztracio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jelszomegint_regisztracio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(Button_kesz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nev_regisztracioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nev_regisztracioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nev_regisztracioActionPerformed

    private void regSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regSubmitButtonActionPerformed

    }//GEN-LAST:event_regSubmitButtonActionPerformed

    private void Button_keszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_keszActionPerformed
//        String username = nev_regisztracio.getText();
//        String password = String.copyValueOf(jelszo_regisztracio.getPassword());
        
//        try {
//            AFP_Labor_A_Kliens.db.connect();
//            if(AFP_Labor_A_Kliens.db.reg_insert(username, password)) {
//                JOptionPane.showMessageDialog(rootPane, "Sikeres Regisztráció!", "Sikeres regisztráció", JOptionPane.PLAIN_MESSAGE);
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "Sikertelen regisztráció: Már létezik ilyen felhasználónév.", "Hiba", JOptionPane.ERROR_MESSAGE);
//            }
//            AFP_Labor_A_Kliens.db.close();
            
            //db.reg_insert(username, password);
            
                    try {
                        
                        
            AFP_Labor_A_Kliens.db.connect();
//            if(AFP_Labor_A_Kliens.db.reg_insert(username, password)) {
//                JOptionPane.showMessageDialog(rootPane, "Sikeres Regisztráció!", "Sikeres regisztráció", JOptionPane.PLAIN_MESSAGE);
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "Sikertelen regisztráció: Már létezik ilyen felhasználónév.", "Hiba", JOptionPane.ERROR_MESSAGE);
//            }
            AFP_Labor_A_Kliens.db.close();
            
            if (String.copyValueOf(jelszo_regisztracio.getPassword()) == String.copyValueOf(jelszomegint_regisztracio.getPassword())){
            
            AFP_Labor_A_Kliens.fukk = "regisztracio$$$" + nev_regisztracio.getText() + "$$$" + String.copyValueOf(jelszo_regisztracio.getPassword());
            
            }
            
            else
            {
            JOptionPane.showMessageDialog(rootPane, "A jelszó nem egyezik a két mezőben!", "Hiba", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_keszActionPerformed

    private void Button_kilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_kilepesActionPerformed
        dispose();
    }//GEN-LAST:event_Button_kilepesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_kesz;
    private javax.swing.JButton Button_kilepes;
    private javax.swing.JTextPane copyright;
    private javax.swing.JPasswordField jelszo_regisztracio;
    private javax.swing.JPasswordField jelszomegint_regisztracio;
    private javax.swing.JTextField nev_regisztracio;
    private javax.swing.JTextPane regisztralas_szoveg;
    // End of variables declaration//GEN-END:variables
}
