-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 09:08:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`varos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`varos` (
  `irsz` INT NOT NULL,
  `nev` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `irsz_UNIQUE` (`irsz` ASC) VISIBLE,
  PRIMARY KEY (`nev`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dolgozo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dolgozo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nev` VARCHAR(45) NOT NULL,
  `szul_ev` INT NOT NULL,
  `fizetes` INT NOT NULL,
  `varos` VARCHAR(45) NOT NULL,
  `utca_hsz` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `varos_nev_irsz_idx` (`varos` ASC) VISIBLE,
  CONSTRAINT `varos_nev_irsz`
    FOREIGN KEY (`varos`)
    REFERENCES `mydb`.`varos` (`nev`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`felhasznalo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`felhasznalo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
